root: ./docs-api/

​structure:
    readme: README.md
    summary: SUMMARY.md​

redirects:
    frontity-cli/environment-variables: ./frontity-cli/README.md
    frontity-packages/frontity: ./frontity-packages/core-package/frontity.md